const axios = require("axios");
const fs = require("fs-extra");
const path = require("path");

module.exports = {
  config: {
    name: "search",
    aliases: ["search"],
    version: "1.0.0",
    author: "Vex_Kshitiz",
    role: 0,
    countDown: 5,
    shortDescription: {
      en: "search image generated by ai",
    },
    longDescription: {
      en: "search ai generated images",
    },
    category: "ai",
    guide: {
      en: "{p}search <search query> -<number of images>",
    },
  },

  onStart: async function ({ api, event, args, config }) {
    try {

      api.setMessageReaction("🔍", event.messageID, (err) => {}, true);

      const keySearch = args.join(" ");
      if (!keySearch.includes("-")) {
        return api.sendMessage(
          `Please enter the search query and the number of images ${config.guide.en}`,
          event.threadID,
          event.messageID
        );
      }
      const keySearchs = keySearch.substr(0, keySearch.indexOf("-")).trim();
      const numberSearch =
        parseInt(keySearch.split("-").pop().trim()) || 6;

      const apiUrl = `https://aiimage-search.vercel.app/kshitiz?search=${encodeURIComponent(
        keySearchs
      )}`;

      const response = await axios.get(apiUrl);
      const data = response.data;

      if (data.length === 0) {
        return api.sendMessage(
          `No images found for "${keySearchs}"`,
          event.threadID,
          event.messageID
        );
      }

      const imgData = [];

      for (let i = 0; i < Math.min(numberSearch, data.length); i++) {
        const imgResponse = await axios.get(data[i], {
          responseType: "arraybuffer",
        });
        const imgPath = path.join(__dirname, "cache", `${i + 1}.jpg`);
        await fs.outputFile(imgPath, imgResponse.data);
        imgData.push(fs.createReadStream(imgPath));
      }

      await api.sendMessage(
        {
          attachment: imgData,
          body: `ai generated images🥱`,
        },
        event.threadID,
        event.messageID
      );

    } catch (error) {
      console.error(error);
      return api.sendMessage(
        `error`,
        event.threadID,
        event.messageID
      );
    }
  },
};
